version: "3.4"

services:
  database:
    image: postgres:14.2
    environment:
      POSTGRES_DB: flowable
      POSTGRES_USER: flowable
      POSTGRES_PASSWORD: flowable
    volumes:
      - data_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      discovery.type: single-node
      node.name: flowable-node-01
      cluster.name: flowable-cluster
      xpack.security.enabled: "false"
    volumes:
      - data_es:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  flowable-design:
    image: artifacts.flowable.com/flowable/flowable-design:latest
    environment:
      flowable.design.remote.authentication.user: admin
      flowable.design.remote.authentication.password: test
      flowable.design.remote.idm-url: http://host.docker.internal:8080
      flowable.design.deployment-api-url: http://host.docker.internal:8080/app-api
      flowable.design.undeployment-api-url: http://host.docker.internal:8080/platform-api/app-deployments
      server.servlet.context-path: /
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.url: jdbc:postgresql://database:5432/flowable
      spring.datasource.username: flowable
      spring.datasource.password: flowable
    ports:
      - 8091:8080
    depends_on:
      - database

  flowable-control:
    image: artifacts.flowable.com/flowable/flowable-control:latest
    environment:
      flowable.common.app.idm-admin.user: admin
      flowable.common.app.idm-admin.password: test
      flowable.control.app.cluster-config.server-address: http://host.docker.internal
      flowable.control.app.cluster-config.port: 8080
      flowable.control.app.cluster-config.context-root: /
      flowable.control.app.cluster-config.password: test
      server.servlet.context-path: /
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.url: jdbc:postgresql://database:5432/flowable
      spring.datasource.username: flowable
      spring.datasource.password: flowable
    ports:
      - 8092:8080
    depends_on:
      - database

volumes:
  data_db:
  data_es:
  data_work:
