# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# The values retrieved from the application.properties represent:
# - properties that may vary depending on deployment
# - build properties retrieved via maven properties


#################################
# Management server configuration
#################################

management:
  server:
    context-path: /
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - info
          - metrics
          - version
          - prometheus
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    info:
      enabled: true
    version:
      enabled: true
  info:
    env:
      enabled: true
